import { GoogleAnalytics } from '@next/third-parties/google';
import localFont from 'next/font/local';
import './globals.css';

import Header from './components/Header';
import ThemeProvider from './components/ThemeProvider';
import cn from './utils/cn';

import type { Metadata } from 'next';
import type { PropsWithChildren } from 'react';

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

const metadata: Metadata = {
  title: 'fanxy',
  description: 'Generated by create next app',
  other: {
    'naver-site-verification': '56ed555c7d847aa18c535618e9d4fbe64ae6b7d4',
  },
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={cn(pretendard.className, 'antialiased')}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          <main className="mx-auto flex w-full max-w-2xl flex-1 flex-col px-6">
            {children}
          </main>
        </ThemeProvider>
      </body>
      <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GA_ID ?? ''} />
    </html>
  );
};

export default RootLayout;
export { metadata };
