import localFont from 'next/font/local';
import './globals.css';

import cn from '~/utils/cn';

import type { Metadata } from 'next';
import type { PropsWithChildren } from 'react';

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

const metadata: Metadata = {
  title: 'Fanxy',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="ko">
      <body className={cn(pretendard.className, 'antialiased')}>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
export { metadata };
