import localFont from 'next/font/local';
import './globals.css';

import ThemeProvider from '~/app/components/ThemeProvider';
import cn from '~/app/utils/cn';

import type { Metadata } from 'next';
import type { PropsWithChildren } from 'react';

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

const metadata: Metadata = {
  title: 'Fanxy',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: PropsWithChildren) => {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={cn(pretendard.className, 'antialiased')}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
export { metadata };
